_wandb:
    value:
        cli_version: 0.21.3
        e:
            mbq76ecnvc1x26p4q160x1ox0zhrt8jj:
                args:
                    - --num-gpus
                    - "1"
                    - --resume
                    - --config-file
                    - /home/mrajaraman/master-thesis-dragonfly/mask-rcnn/Mask-RCNN-MassID45/configs/new_baselines/mask_rcnn_R_50_FPN_100ep_LSJ.py--exp_id
                    - --dataset_path
                    - /h/jquinto/MaskDINO/datasets/lifeplan_/
                    - train.output_dir=output__sahi_tiled_v9_scratch
                    - train.init_checkpoint=detectron2://ImageNetPretrained/torchvision/R-50.pkl
                    - dataloader.train.dataset.names=/home/mrajaraman/do-not-modify/image-to-coco-json-converter/output/train.json
                    - dataloader.test.dataset.names=/home/mrajaraman/do-not-modify/image-to-coco-json-converter/output/val.json
                email: mrnalini@live.in
                executable: /home/mrajaraman/conda/mask_rcnn/bin/python
                git:
                    commit: 2d140ac385db07473682749d282a28d690cfb4a3
                    remote: https://github.com/itismeganrms/master-thesis-dragonfly.git
                host: node868
                os: Linux-5.14.0-427.26.1.el9_4.x86_64-x86_64-with-glibc2.17
                program: /home/mrajaraman/master-thesis-dragonfly/mask-rcnn/Mask-RCNN-MassID45/tools/lazyconfig_train_net.py
                python: CPython 3.8.20
                root: /zfsstore/user/mrajaraman/master-thesis-dragonfly/mask-rcnn/Mask-RCNN-MassID45
                startedAt: "2025-09-04T16:47:17.967286Z"
                writerId: mbq76ecnvc1x26p4q160x1ox0zhrt8jj
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 43
            "2":
                - 1
                - 41
                - 43
            "3":
                - 15
                - 16
            "4": 3.8.20
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
architecture:
    value: Mask-R-CNN
